name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate --force

      - name: Build Nuxt app
        run: npm run build

      - name: Archive build output
        run: tar -czf output.tar.gz .output

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload .output to VPS
        run: scp -o StrictHostKeyChecking=no output.tar.gz tesdap@5.249.254.245:/home/tesdap/portfolio-website/

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no tesdap@5.249.254.245 << 'EOF'
            cd portfolio-website
            rm -rf .output
            tar -xzf output.tar.gz
            rm output.tar.gz
            sudo systemctl restart portfolio-website.service
          EOF
